### ISSUE TITLE
Adobe Acrobat 无效，只是显示Premium ，但是激活不了Premium 的功能

### ISSUE THREAD

**Issue by oniyou** [WeeekWin/Quanx#4]
![image](https://user-images.githubusercontent.com/39154346/201427645-99a33fc4-af6d-49b8-b65d-ffc3907fbe20.png)

**Comment by oniyou** [comment]
这个页面始终解锁不了～
![image](https://user-images.githubusercontent.com/39154346/201428718-d8b8e9b9-8c7a-41ea-aa17-8ce5b6cb7d02.jpeg)
![image](https://user-images.githubusercontent.com/39154346/201428763-c6e326c3-08e1-4835-bb7c-1641f9236cab.png)

**Comment by WeeekWin** [comment]
Sorry,I didn't test it because of time,maybe u can try to open a trial membership? I'll try testing with a new account shortly.Thanks u for using.
